version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .live.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  ytc-back-prod:
    container_name: ytc-back-prod
    image: ytc-back-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh ./entrypoint.sh
    ports: 
      - 8000:8000
    depends_on:
      - db


# volumes:
#   production_db_volume: